[package]
name = "generic_vec"
version = "0.1.0"
edition = "2021"

[dependencies]
buffers = { path = "../2_buffers" }
test_utils = { path = "../a_test_utils" }

[features]
default = ["allocator"]
allocator = ["buffers/allocator"]
